set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

# Keep OpenCV on a conservative CPU path for this local MinGW toolchain.
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DCV_ENABLE_INTRINSICS=OFF
    -DWITH_IPP=OFF
    -DBUILD_IPP_IW=OFF
    -DWITH_OPENMP=OFF
    -DWITH_TBB=OFF
    -DCPU_DISPATCH=
    -DCPU_BASELINE=SSE3
)
